//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weldings.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.3.0.0")]
    internal sealed partial class Messages : global::System.Configuration.ApplicationSettingsBase {
        
        private static Messages defaultInstance = ((Messages)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Messages())));
        
        public static Messages Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Pasikartojantys suvirinimai: ")]
        public string RepeatedRecordsHeader {
            get {
                return ((string)(this["RepeatedRecordsHeader"]));
            }
            set {
                this["RepeatedRecordsHeader"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Operatorius: {0}, lentelė: \"{1}\". ")]
        public string OperSheetFrmt {
            get {
                return ((string)(this["OperSheetFrmt"]));
            }
            set {
                this["OperSheetFrmt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Google Sheets data fetch FAIL")]
        public string GSDataFetchFail {
            get {
                return ((string)(this["GSDataFetchFail"]));
            }
            set {
                this["GSDataFetchFail"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Verify Operation Error")]
        public string VerifyOperationErrorMsgTitle {
            get {
                return ((string)(this["VerifyOperationErrorMsgTitle"]));
            }
            set {
                this["VerifyOperationErrorMsgTitle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Yra blogų duomenų Google Sheets")]
        public string BadGSData {
            get {
                return ((string)(this["BadGSData"]));
            }
            set {
                this["BadGSData"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Nepavyksta Google Sheets lentelės duomenų paversti tinkamais įrašyti į DB")]
        public string GSDataConvertFail {
            get {
                return ((string)(this["GSDataConvertFail"]));
            }
            set {
                this["GSDataConvertFail"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Google Sheets duomenų patikrinimo rezultatas: ")]
        public string GSDataVerifyResult {
            get {
                return ((string)(this["GSDataVerifyResult"]));
            }
            set {
                this["GSDataVerifyResult"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"DĖMESIO! Kadangi duomenys į duomenų bazę sukelti, tie duomenys bus įtraukti į ataskaitą, kaip sutvarkyti. TAČIAU Google Sheets lentelę reikėtų sutvarkyti rankiniu būdu - prisijungti prie Google Sheets, atsidaryti lentelę ir joje pažymėti, kurie duomenys yra sukelti į DB.")]
        public string GSUpdateFailInstruction {
            get {
                return ((string)(this["GSUpdateFailInstruction"]));
            }
            set {
                this["GSUpdateFailInstruction"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Google Sheets update FAIL")]
        public string GSUpdateFail {
            get {
                return ((string)(this["GSUpdateFail"]));
            }
            set {
                this["GSUpdateFail"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Google Sheets update OK")]
        public string GSUpdateOK {
            get {
                return ((string)(this["GSUpdateOK"]));
            }
            set {
                this["GSUpdateOK"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DB update OK")]
        public string DBUpdateOK {
            get {
                return ((string)(this["DBUpdateOK"]));
            }
            set {
                this["DBUpdateOK"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DB update FAIL, transaction rollback OK")]
        public string DBUpdateFailTransOK {
            get {
                return ((string)(this["DBUpdateFailTransOK"]));
            }
            set {
                this["DBUpdateFailTransOK"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DB update FAIL, transaction rollback FAIL")]
        public string DBUpdateFailTransFail {
            get {
                return ((string)(this["DBUpdateFailTransFail"]));
            }
            set {
                this["DBUpdateFailTransFail"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Failure info: ")]
        public string FailureInfo {
            get {
                return ((string)(this["FailureInfo"]));
            }
            set {
                this["FailureInfo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Google Sheets data verify FAIL")]
        public string GSDataVerifyFail {
            get {
                return ((string)(this["GSDataVerifyFail"]));
            }
            set {
                this["GSDataVerifyFail"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Google Sheets data verify OK")]
        public string GSDataVerifyOK {
            get {
                return ((string)(this["GSDataVerifyOK"]));
            }
            set {
                this["GSDataVerifyOK"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DB Update Operation Error")]
        public string UpdateOperationErrorMsgTitle {
            get {
                return ((string)(this["UpdateOperationErrorMsgTitle"]));
            }
            set {
                this["UpdateOperationErrorMsgTitle"] = value;
            }
        }
    }
}
