//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weldings.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.3.0.0")]
    internal sealed partial class StartFormMessages : global::System.Configuration.ApplicationSettingsBase {
        
        private static StartFormMessages defaultInstance = ((StartFormMessages)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new StartFormMessages())));
        
        public static StartFormMessages Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Cannot create the output folder  \"{0}\". Try to create it manually.\\n")]
        public string CannotCreateOutputFolder {
            get {
                return ((string)(this["CannotCreateOutputFolder"]));
            }
            set {
                this["CannotCreateOutputFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Create Folder Error")]
        public string CreateFolderErrorTitle {
            get {
                return ((string)(this["CreateFolderErrorTitle"]));
            }
            set {
                this["CreateFolderErrorTitle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Verifying {0}, {1}")]
        public string DataVerifyOutputHeaderFormat {
            get {
                return ((string)(this["DataVerifyOutputHeaderFormat"]));
            }
            set {
                this["DataVerifyOutputHeaderFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Unexpected exception: ")]
        public string UnexpectedExceptionHeader {
            get {
                return ((string)(this["UnexpectedExceptionHeader"]));
            }
            set {
                this["UnexpectedExceptionHeader"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Verify Error")]
        public string DataVerifyErrorTitle {
            get {
                return ((string)(this["DataVerifyErrorTitle"]));
            }
            set {
                this["DataVerifyErrorTitle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tikrinimas atliktas. Dabar bus atidarytas failas su tikrinimo eiga ir išvardintom" +
            "is problemomis.")]
        public string VerifyDoneMessage {
            get {
                return ((string)(this["VerifyDoneMessage"]));
            }
            set {
                this["VerifyDoneMessage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Task Accomplished")]
        public string TaskAccomplishedTitle {
            get {
                return ((string)(this["TaskAccomplishedTitle"]));
            }
            set {
                this["TaskAccomplishedTitle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Unable to create database file copy: \\n\\tfrom: \"{0}\"\\n\\tto: \"{1}\"\\n\\n")]
        public string UnableCreateDBCopy {
            get {
                return ((string)(this["UnableCreateDBCopy"]));
            }
            set {
                this["UnableCreateDBCopy"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("File Copy Error")]
        public string FileCopyErrorTitle {
            get {
                return ((string)(this["FileCopyErrorTitle"]));
            }
            set {
                this["FileCopyErrorTitle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Updating {0}, {1}")]
        public string DataUpdateOutputHeaderFormat {
            get {
                return ((string)(this["DataUpdateOutputHeaderFormat"]));
            }
            set {
                this["DataUpdateOutputHeaderFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Operation aborted after rollback failure of unusuccessful update transaction")]
        public string RollbackFailureError {
            get {
                return ((string)(this["RollbackFailureError"]));
            }
            set {
                this["RollbackFailureError"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Operation Aborted")]
        public string OperationAbortedTitle {
            get {
                return ((string)(this["OperationAbortedTitle"]));
            }
            set {
                this["OperationAbortedTitle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DB Update Error")]
        public string UpdateErrorTitle {
            get {
                return ((string)(this["UpdateErrorTitle"]));
            }
            set {
                this["UpdateErrorTitle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Nepavyko įrašyti informacijos apie update procesą į \"{0}\"\\n")]
        public string UnableWriteUpdateInfoFile {
            get {
                return ((string)(this["UnableWriteUpdateInfoFile"]));
            }
            set {
                this["UnableWriteUpdateInfoFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("File Write Error")]
        public string FileWriteErrorTitle {
            get {
                return ((string)(this["FileWriteErrorTitle"]));
            }
            set {
                this["FileWriteErrorTitle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Nepavyko įrašyti informacijos apie verify procesą į \"{0}\"\\n")]
        public string UnableWriteVerifyInfoFile {
            get {
                return ((string)(this["UnableWriteVerifyInfoFile"]));
            }
            set {
                this["UnableWriteVerifyInfoFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Nepavyko įrašyti update suvestinės į \"{0}\"\\n")]
        public string UnableWriteUpdateReportFile {
            get {
                return ((string)(this["UnableWriteUpdateReportFile"]));
            }
            set {
                this["UnableWriteUpdateReportFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Select database file")]
        public string OpenFileDialogTitle {
            get {
                return ((string)(this["OpenFileDialogTitle"]));
            }
            set {
                this["OpenFileDialogTitle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Select output folder")]
        public string SelectFolderDialogTitle {
            get {
                return ((string)(this["SelectFolderDialogTitle"]));
            }
            set {
                this["SelectFolderDialogTitle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Bad {0} file name format \"{1}\"\\n")]
        public string BadFileNameFormatMessage {
            get {
                return ((string)(this["BadFileNameFormatMessage"]));
            }
            set {
                this["BadFileNameFormatMessage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Bad String Format")]
        public string BadStringFormatErrorTitle {
            get {
                return ((string)(this["BadStringFormatErrorTitle"]));
            }
            set {
                this["BadStringFormatErrorTitle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".txt")]
        public string OutputFileExtension {
            get {
                return ((string)(this["OutputFileExtension"]));
            }
            set {
                this["OutputFileExtension"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Settings saved")]
        public string SettingsSavedMsg {
            get {
                return ((string)(this["SettingsSavedMsg"]));
            }
            set {
                this["SettingsSavedMsg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Operation Success")]
        public string SettingsSavedBoxTitle {
            get {
                return ((string)(this["SettingsSavedBoxTitle"]));
            }
            set {
                this["SettingsSavedBoxTitle"] = value;
            }
        }
    }
}
